# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Renogy BT
description: Monitor Renogy solar devices via Bluetooth
version: "0.1.0"
slug: renogy-bt
url: "https://github.com/jtoniolo/renogy-ha-addon/tree/main/renogy-bt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
map:
  - bluetooth:ro
services:
  - mqtt:need
options:
  scan_interval: 60
  mqtt:
    topic_prefix: "renogy"
    discovery: true
  bluetooth:
    auto_discover: true
    known_devices: []
  temperature_unit: "C"
  debug: false
schema:
  scan_interval: int(10,600)
  mqtt:
    topic_prefix: str
    discovery: bool
  bluetooth:
    auto_discover: bool
    known_devices:
      - name: str?
        mac_address: str
        device_type: list(rover|rover_history|battery|inverter|dc_charger)
        device_id: int(1,255)?
  temperature_unit: list(C|F)
  debug: bool
image: "ghcr.io/jtoniolo/{arch}-addon-renogy-bt"
