# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Renogy Monitor Add-on
version: "1.2.0"
slug: renogy-monitor
description: Renogy Monitor add-on for Home Assistant.
url: "https://github.com/jtoniolo/renogy-ha-addon/tree/main/renogy-monitor"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
map:
  - share:ro
host_dbus: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
apparmor: false  # Disable AppArmor for Bluetooth access
services:
  - mqtt:need
options:
  scan_interval: 60
  mqtt:
    topic_prefix: "renogy"
    discovery: true
  bluetooth:
    auto_discover: true
    known_devices: []
  temperature_unit: "C"
  debug: false
schema:
  scan_interval: "int(10,600)"
  mqtt:
    topic_prefix: "str"
    discovery: "bool"
  bluetooth:
    auto_discover: "bool"
    known_devices:
      - name: "str?"
        mac_address: "str"
        device_type: "list(rover|rover_history|battery|inverter|dc_charger)"
        device_id: "int(1,255)?"
  temperature_unit: "list(C|F)"
  debug: "bool"

