# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Renogy Monitor Add-on
version: "1.2.0"
slug: renogy-monitor
description: Renogy Monitor add-on for Home Assistant.
url: "https://github.com/jtoniolo/renogy-ha-addon/tree/main/renogy-monitor"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
services:
  - mqtt:need
options:
  message: "Hello world..."
schema:
  message: "str?"
